#include "filters.h"
#include "../compress/deflate.h"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <limits.h>
#include <stdint.h>

// Stream-filter chain, moved verbatim from src/reader/tspr_xref.c. The four
// inline decoders (ASCIIHex/ASCII85/RunLength/LZW), the FlateDecode predictor
// post-processing, and the dispatch preserve every bound check, output cap, and
// filter-name abbreviation alias (AHx, A85, RL, LZW, Fl).
//
// Local copy of the pure dict walk so this module keeps the dependency arrow
// pointing reader -> filters: it walks only the public TspdfObj/TspdfDictEntry
// fields and never reaches into tspr_internal.h. Identical semantics to the
// reader's tspdf_dict_get (last-writer-wins on duplicate keys).
static TspdfObj *filter_dict_get(TspdfObj *dict, const char *key) {
    if (!dict || dict->type != TSPDF_OBJ_DICT) return NULL;
    for (size_t i = dict->dict.count; i > 0; i--) {
        size_t idx = i - 1;
        if (strcmp(dict->dict.entries[idx].key, key) == 0)
            return dict->dict.entries[idx].value;
    }
    return NULL;
}

static TspdfObj *decode_params_at(TspdfObj *stream_dict, size_t filter_index) {
    TspdfObj *params = filter_dict_get(stream_dict, "DecodeParms");
    if (!params) {
        params = filter_dict_get(stream_dict, "DP");
    }
    if (!params || params->type == TSPDF_OBJ_NULL) {
        return NULL;
    }

    if (params->type == TSPDF_OBJ_DICT) {
        (void)filter_index;
        return params;
    }

    if (params->type == TSPDF_OBJ_ARRAY && filter_index < params->array.count) {
        TspdfObj *entry = &params->array.items[filter_index];
        if (entry->type == TSPDF_OBJ_DICT) {
            return entry;
        }
    }

    return NULL;
}

static bool decode_param_int(TspdfObj *params, const char *key, int default_value, int *out) {
    *out = default_value;
    if (!params) {
        return true;
    }

    TspdfObj *obj = filter_dict_get(params, key);
    if (!obj) {
        return true;
    }
    if (obj->type != TSPDF_OBJ_INT || obj->integer < 0 || obj->integer > INT_MAX) {
        return false;
    }

    *out = (int)obj->integer;
    return true;
}

static uint8_t paeth_predictor(uint8_t a, uint8_t b, uint8_t c) {
    int p = (int)a + (int)b - (int)c;
    int pa = abs(p - (int)a);
    int pb = abs(p - (int)b);
    int pc = abs(p - (int)c);

    if (pa <= pb && pa <= pc) return a;
    if (pb <= pc) return b;
    return c;
}

static void decode_png_predictor_row(uint8_t *dst, const uint8_t *src,
                                     const uint8_t *prev, size_t row_len,
                                     size_t bytes_per_pixel, uint8_t filter) {
    for (size_t i = 0; i < row_len; i++) {
        uint8_t left = (i >= bytes_per_pixel) ? dst[i - bytes_per_pixel] : 0;
        uint8_t up = prev ? prev[i] : 0;
        uint8_t up_left = (prev && i >= bytes_per_pixel) ? prev[i - bytes_per_pixel] : 0;
        uint8_t predicted = 0;

        switch (filter) {
            case 0: predicted = 0; break;
            case 1: predicted = left; break;
            case 2: predicted = up; break;
            case 3: predicted = (uint8_t)(((int)left + (int)up) / 2); break;
            case 4: predicted = paeth_predictor(left, up, up_left); break;
            default: predicted = 0; break;
        }

        dst[i] = (uint8_t)(src[i] + predicted);
    }
}

static TspdfError apply_flate_decode_params(TspdfObj *params, uint8_t **data, size_t *len) {
    int predictor = 1;
    int colors = 1;
    int bits_per_component = 8;
    int columns = 1;
    if (!decode_param_int(params, "Predictor", 1, &predictor) ||
        !decode_param_int(params, "Colors", 1, &colors) ||
        !decode_param_int(params, "BitsPerComponent", 8, &bits_per_component) ||
        !decode_param_int(params, "Columns", 1, &columns)) {
        return TSPDF_ERR_XREF;
    }

    if (predictor <= 1) {
        return TSPDF_OK;
    }
    if (!data || !*data || !len || colors <= 0 || columns <= 0 || bits_per_component <= 0) {
        return TSPDF_ERR_XREF;
    }

    // XRef and object streams generated by pdfTeX use 8-bit PNG predictors.
    // Other bit depths need bit-level sample handling, so reject them clearly.
    if (bits_per_component != 8) {
        return TSPDF_ERR_UNSUPPORTED;
    }

    if ((size_t)columns > SIZE_MAX / (size_t)colors) {
        return TSPDF_ERR_XREF;
    }
    size_t samples = (size_t)columns * (size_t)colors;
    if (samples > (SIZE_MAX - 7) / (size_t)bits_per_component) {
        return TSPDF_ERR_XREF;
    }
    size_t row_len = (samples * (size_t)bits_per_component + 7) / 8;
    size_t bytes_per_pixel = ((size_t)colors * (size_t)bits_per_component + 7) / 8;
    if (row_len == 0 || bytes_per_pixel == 0) {
        return TSPDF_ERR_XREF;
    }

    uint8_t *out = NULL;
    size_t out_len = 0;

    if (predictor == 2) {
        if (*len % row_len != 0) {
            return TSPDF_ERR_XREF;
        }
        out_len = *len;
        out = (uint8_t *)malloc(out_len);
        if (!out && out_len > 0) {
            return TSPDF_ERR_ALLOC;
        }

        size_t rows = *len / row_len;
        for (size_t r = 0; r < rows; r++) {
            const uint8_t *src = *data + r * row_len;
            uint8_t *dst = out + r * row_len;
            decode_png_predictor_row(dst, src, NULL, row_len, bytes_per_pixel, 1);
        }
    } else if (predictor >= 10 && predictor <= 15) {
        size_t tagged_row_len = row_len + 1;

        if (*len % tagged_row_len == 0) {
            size_t rows = *len / tagged_row_len;
            out_len = rows * row_len;
            out = (uint8_t *)malloc(out_len);
            if (!out && out_len > 0) {
                return TSPDF_ERR_ALLOC;
            }

            const uint8_t *prev = NULL;
            for (size_t r = 0; r < rows; r++) {
                const uint8_t *src = *data + r * tagged_row_len;
                uint8_t filter = src[0];
                if (filter > 4) {
                    free(out);
                    return TSPDF_ERR_XREF;
                }

                uint8_t *dst = out + r * row_len;
                decode_png_predictor_row(dst, src + 1, prev, row_len, bytes_per_pixel, filter);
                prev = dst;
            }
        } else if (predictor <= 14 && *len % row_len == 0) {
            size_t rows = *len / row_len;
            out_len = *len;
            out = (uint8_t *)malloc(out_len);
            if (!out && out_len > 0) {
                return TSPDF_ERR_ALLOC;
            }

            const uint8_t *prev = NULL;
            uint8_t filter = (uint8_t)(predictor - 10);
            for (size_t r = 0; r < rows; r++) {
                const uint8_t *src = *data + r * row_len;
                uint8_t *dst = out + r * row_len;
                decode_png_predictor_row(dst, src, prev, row_len, bytes_per_pixel, filter);
                prev = dst;
            }
        } else {
            return TSPDF_ERR_XREF;
        }
    } else {
        return TSPDF_ERR_UNSUPPORTED;
    }

    free(*data);
    *data = out;
    *len = out_len;
    return TSPDF_OK;
}

static TspdfError decode_ascii_hex(const uint8_t *data, size_t len,
                                   uint8_t **out, size_t *out_len) {
    size_t cap = len / 2 + 2;
    uint8_t *buf = (uint8_t *)malloc(cap);
    if (!buf) {
        return TSPDF_ERR_ALLOC;
    }

    size_t pos = 0;
    int high = -1;
    for (size_t i = 0; i < len; i++) {
        uint8_t c = data[i];
        if (c == '>') {
            break;
        }
        if (c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\0' || c == '\f') {
            continue;
        }

        int value;
        if (c >= '0' && c <= '9') value = c - '0';
        else if (c >= 'a' && c <= 'f') value = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') value = c - 'A' + 10;
        else {
            free(buf);
            return TSPDF_ERR_XREF;
        }

        if (high < 0) {
            high = value;
        } else {
            if (pos >= cap) {
                free(buf);
                return TSPDF_ERR_XREF;
            }
            buf[pos++] = (uint8_t)((high << 4) | value);
            high = -1;
        }
    }

    if (high >= 0) {
        if (pos >= cap) {
            free(buf);
            return TSPDF_ERR_XREF;
        }
        buf[pos++] = (uint8_t)(high << 4);
    }

    *out = buf;
    *out_len = pos;
    return TSPDF_OK;
}

static bool ensure_decode_capacity(uint8_t **buf, size_t *cap, size_t len, size_t extra) {
    if (extra > SIZE_MAX - len) {
        return false;
    }
    size_t needed = len + extra;
    if (needed <= *cap) {
        return true;
    }

    size_t new_cap = *cap ? *cap : 256;
    while (new_cap < needed) {
        if (new_cap > SIZE_MAX / 2) {
            new_cap = needed;
            break;
        }
        new_cap *= 2;
    }

    uint8_t *new_buf = (uint8_t *)realloc(*buf, new_cap);
    if (!new_buf) {
        return false;
    }
    *buf = new_buf;
    *cap = new_cap;
    return true;
}

static TspdfError decode_ascii85(const uint8_t *data, size_t len,
                                 uint8_t **out, size_t *out_len) {
    if (len > SIZE_MAX - 4) {
        return TSPDF_ERR_XREF;
    }

    size_t cap = len + 4;
    uint8_t *buf = (uint8_t *)malloc(cap);
    if (!buf) {
        return TSPDF_ERR_ALLOC;
    }

    size_t pos = 0;
    uint32_t digits[5];
    size_t count = 0;
    bool eod = false;

    for (size_t i = 0; i < len; i++) {
        uint8_t c = data[i];
        if (c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\0' || c == '\f') {
            continue;
        }

        if (c == '~') {
            size_t j = i + 1;
            while (j < len && (data[j] == ' ' || data[j] == '\t' ||
                               data[j] == '\r' || data[j] == '\n' ||
                               data[j] == '\0' || data[j] == '\f')) {
                j++;
            }
            if (j >= len || data[j] != '>') {
                free(buf);
                return TSPDF_ERR_XREF;
            }
            eod = true;
            break;
        }

        if (c == 'z') {
            if (count != 0) {
                free(buf);
                return TSPDF_ERR_XREF;
            }
            if (!ensure_decode_capacity(&buf, &cap, pos, 4)) {
                free(buf);
                return TSPDF_ERR_ALLOC;
            }
            buf[pos++] = 0;
            buf[pos++] = 0;
            buf[pos++] = 0;
            buf[pos++] = 0;
            continue;
        }

        if (c < '!' || c > 'u') {
            free(buf);
            return TSPDF_ERR_XREF;
        }

        digits[count++] = (uint32_t)(c - '!');
        if (count == 5) {
            uint64_t value = 0;
            for (size_t d = 0; d < 5; d++) {
                value = value * 85 + digits[d];
            }
            if (value > UINT32_MAX) {
                free(buf);
                return TSPDF_ERR_XREF;
            }
            if (!ensure_decode_capacity(&buf, &cap, pos, 4)) {
                free(buf);
                return TSPDF_ERR_ALLOC;
            }
            buf[pos++] = (uint8_t)(value >> 24);
            buf[pos++] = (uint8_t)(value >> 16);
            buf[pos++] = (uint8_t)(value >> 8);
            buf[pos++] = (uint8_t)value;
            count = 0;
        }
    }

    (void)eod;
    if (count == 1) {
        free(buf);
        return TSPDF_ERR_XREF;
    }
    if (count > 1) {
        for (size_t i = count; i < 5; i++) {
            digits[i] = 84;
        }

        uint64_t value = 0;
        for (size_t d = 0; d < 5; d++) {
            value = value * 85 + digits[d];
        }
        if (value > UINT32_MAX) {
            free(buf);
            return TSPDF_ERR_XREF;
        }

        if (!ensure_decode_capacity(&buf, &cap, pos, count - 1)) {
            free(buf);
            return TSPDF_ERR_ALLOC;
        }
        for (size_t i = 0; i < count - 1; i++) {
            buf[pos++] = (uint8_t)(value >> (24 - i * 8));
        }
    }

    *out = buf;
    *out_len = pos;
    return TSPDF_OK;
}

static TspdfError decode_run_length(const uint8_t *data, size_t len,
                                    uint8_t **out, size_t *out_len) {
    size_t cap = len ? len : 1;
    uint8_t *buf = (uint8_t *)malloc(cap);
    if (!buf) {
        return TSPDF_ERR_ALLOC;
    }

    size_t pos = 0;
    for (size_t i = 0; i < len; ) {
        uint8_t control = data[i++];
        if (control == 128) {
            break;
        }

        if (control <= 127) {
            size_t count = (size_t)control + 1;
            if (count > len - i) {
                free(buf);
                return TSPDF_ERR_XREF;
            }
            if (!ensure_decode_capacity(&buf, &cap, pos, count)) {
                free(buf);
                return TSPDF_ERR_ALLOC;
            }
            memcpy(buf + pos, data + i, count);
            pos += count;
            i += count;
        } else {
            size_t count = 257u - (size_t)control;
            if (i >= len) {
                free(buf);
                return TSPDF_ERR_XREF;
            }
            if (!ensure_decode_capacity(&buf, &cap, pos, count)) {
                free(buf);
                return TSPDF_ERR_ALLOC;
            }
            memset(buf + pos, data[i++], count);
            pos += count;
        }
    }

    *out = buf;
    *out_len = pos;
    return TSPDF_OK;
}

typedef struct {
    const uint8_t *data;
    size_t len;
    size_t bit_pos;
} LzwBitReader;

static bool lzw_read_code(LzwBitReader *reader, int bits, uint16_t *out_code) {
    if (!reader || !out_code || bits <= 0 || bits > 12 ||
        reader->len > SIZE_MAX / 8) {
        return false;
    }

    size_t total_bits = reader->len * 8;
    if (reader->bit_pos > total_bits ||
        (size_t)bits > total_bits - reader->bit_pos) {
        return false;
    }

    uint16_t value = 0;
    for (int i = 0; i < bits; i++) {
        size_t bit = reader->bit_pos++;
        uint8_t byte = reader->data[bit / 8];
        value = (uint16_t)((value << 1) | ((byte >> (7 - (bit % 8))) & 1u));
    }

    *out_code = value;
    return true;
}

static void lzw_reset_table(uint16_t *prefix, uint8_t *suffix,
                            size_t *next_code, int *code_size) {
    for (size_t i = 0; i < 256; i++) {
        prefix[i] = 0;
        suffix[i] = (uint8_t)i;
    }
    *next_code = 258;
    *code_size = 9;
}

static bool lzw_expand_code(uint16_t code, size_t next_code,
                            const uint16_t *prefix, const uint8_t *suffix,
                            uint8_t *sequence, size_t *sequence_len,
                            uint8_t *first_char) {
    uint8_t stack[4096];
    size_t stack_len = 0;
    uint16_t current = code;

    while (current >= 258) {
        if ((size_t)current >= next_code || stack_len >= sizeof(stack)) {
            return false;
        }
        stack[stack_len++] = suffix[current];
        current = prefix[current];
    }

    if (current >= 256 || stack_len >= sizeof(stack)) {
        return false;
    }

    stack[stack_len++] = (uint8_t)current;
    *first_char = (uint8_t)current;

    for (size_t i = 0; i < stack_len; i++) {
        sequence[i] = stack[stack_len - 1 - i];
    }
    *sequence_len = stack_len;
    return true;
}

static void lzw_maybe_grow_code_size(size_t next_code, int early_change,
                                     int *code_size) {
    if (*code_size < 12 &&
        next_code + (size_t)early_change >= ((size_t)1 << *code_size)) {
        (*code_size)++;
    }
}

static TspdfError decode_lzw(const uint8_t *data, size_t len,
                             TspdfObj *params,
                             uint8_t **out, size_t *out_len) {
    int early_change = 1;
    if (!decode_param_int(params, "EarlyChange", 1, &early_change) ||
        (early_change != 0 && early_change != 1)) {
        return TSPDF_ERR_XREF;
    }

    if (len > SIZE_MAX / 2) {
        return TSPDF_ERR_XREF;
    }
    size_t cap = len ? len * 2 : 1;
    if (cap < 256) cap = 256;

    uint8_t *buf = (uint8_t *)malloc(cap);
    if (!buf) {
        return TSPDF_ERR_ALLOC;
    }

    uint16_t prefix[4096] = {0};
    uint8_t suffix[4096] = {0};
    size_t next_code = 258;
    int code_size = 9;
    lzw_reset_table(prefix, suffix, &next_code, &code_size);

    LzwBitReader reader = {data, len, 0};
    int previous_code = -1;
    size_t pos = 0;

    while (1) {
        uint16_t code = 0;
        if (!lzw_read_code(&reader, code_size, &code)) {
            break;
        }

        if (code == 256) {
            lzw_reset_table(prefix, suffix, &next_code, &code_size);
            previous_code = -1;
            continue;
        }
        if (code == 257) {
            break;
        }

        uint8_t sequence[4096];
        size_t sequence_len = 0;
        uint8_t first_char = 0;
        if ((size_t)code < next_code) {
            if (!lzw_expand_code(code, next_code, prefix, suffix,
                                 sequence, &sequence_len, &first_char)) {
                free(buf);
                return TSPDF_ERR_XREF;
            }
        } else if ((size_t)code == next_code && previous_code >= 0) {
            if (!lzw_expand_code((uint16_t)previous_code, next_code, prefix, suffix,
                                 sequence, &sequence_len, &first_char) ||
                sequence_len >= sizeof(sequence)) {
                free(buf);
                return TSPDF_ERR_XREF;
            }
            sequence[sequence_len++] = first_char;
        } else {
            free(buf);
            return TSPDF_ERR_XREF;
        }

        if (!ensure_decode_capacity(&buf, &cap, pos, sequence_len)) {
            free(buf);
            return TSPDF_ERR_ALLOC;
        }
        memcpy(buf + pos, sequence, sequence_len);
        pos += sequence_len;

        if (previous_code >= 0 && next_code < 4096) {
            prefix[next_code] = (uint16_t)previous_code;
            suffix[next_code] = first_char;
            next_code++;
            lzw_maybe_grow_code_size(next_code, early_change, &code_size);
        }

        previous_code = (int)code;
    }

    *out = buf;
    *out_len = pos;
    return TSPDF_OK;
}

// Decode one filter application by name. `params` is the resolved, direct
// /DecodeParms dict for this filter (or NULL). This is the per-filter body of
// the original decode_stream_data loop, factored so both the public single-shot
// entry point and the chain share the same dispatch and error codes.
uint8_t *tspdf_filter_decode(const char *filter_name,
                             const uint8_t *data, size_t len,
                             TspdfObj *params, size_t *out_len,
                             TspdfError *err) {
    TspdfError local_err = TSPDF_OK;
    if (!err) {
        err = &local_err;
    }
    if (!filter_name || !out_len) {
        *err = TSPDF_ERR_XREF;
        return NULL;
    }

    uint8_t *decoded = NULL;
    size_t decoded_len = 0;

    if (strcmp(filter_name, "ASCIIHexDecode") == 0 ||
        strcmp(filter_name, "AHx") == 0) {
        *err = decode_ascii_hex(data, len, &decoded, &decoded_len);
        if (*err != TSPDF_OK) {
            return NULL;
        }
    } else if (strcmp(filter_name, "ASCII85Decode") == 0 ||
               strcmp(filter_name, "A85") == 0) {
        *err = decode_ascii85(data, len, &decoded, &decoded_len);
        if (*err != TSPDF_OK) {
            return NULL;
        }
    } else if (strcmp(filter_name, "RunLengthDecode") == 0 ||
               strcmp(filter_name, "RL") == 0) {
        *err = decode_run_length(data, len, &decoded, &decoded_len);
        if (*err != TSPDF_OK) {
            return NULL;
        }
    } else if (strcmp(filter_name, "LZWDecode") == 0 ||
               strcmp(filter_name, "LZW") == 0) {
        *err = decode_lzw(data, len, params, &decoded, &decoded_len);
        if (*err != TSPDF_OK) {
            return NULL;
        }

        *err = apply_flate_decode_params(params, &decoded, &decoded_len);
        if (*err != TSPDF_OK) {
            free(decoded);
            return NULL;
        }
    } else if (strcmp(filter_name, "FlateDecode") == 0 ||
               strcmp(filter_name, "Fl") == 0) {
        decoded = deflate_decompress(data, len, &decoded_len);
        if (!decoded) {
            *err = TSPDF_ERR_XREF;
            return NULL;
        }

        *err = apply_flate_decode_params(params, &decoded, &decoded_len);
        if (*err != TSPDF_OK) {
            free(decoded);
            return NULL;
        }
    } else {
        *err = TSPDF_ERR_UNSUPPORTED;
        return NULL;
    }

    *out_len = decoded_len;
    *err = TSPDF_OK;
    return decoded;
}

TspdfError tspdf_filter_decode_chain(TspdfObj *stream_dict,
                                     const uint8_t *raw_data, size_t raw_len,
                                     uint8_t **out_data, size_t *out_len) {
    TspdfObj *filter = filter_dict_get(stream_dict, "Filter");
    if (!filter || filter->type == TSPDF_OBJ_NULL) {
        uint8_t *copy = (uint8_t *)malloc(raw_len ? raw_len : 1);
        if (!copy) {
            return TSPDF_ERR_ALLOC;
        }
        if (raw_len > 0) {
            memcpy(copy, raw_data, raw_len);
        }
        *out_data = copy;
        *out_len = raw_len;
        return TSPDF_OK;
    }

    size_t filter_count = 0;
    if (filter->type == TSPDF_OBJ_NAME) {
        filter_count = 1;
    } else if (filter->type == TSPDF_OBJ_ARRAY) {
        filter_count = filter->array.count;
    } else {
        return TSPDF_ERR_UNSUPPORTED;
    }

    uint8_t *current = (uint8_t *)malloc(raw_len ? raw_len : 1);
    if (!current) {
        return TSPDF_ERR_ALLOC;
    }
    if (raw_len > 0) {
        memcpy(current, raw_data, raw_len);
    }
    size_t current_len = raw_len;

    for (size_t i = 0; i < filter_count; i++) {
        TspdfObj *filter_name = filter->type == TSPDF_OBJ_NAME ? filter : &filter->array.items[i];
        if (!filter_name || filter_name->type != TSPDF_OBJ_NAME) {
            free(current);
            return TSPDF_ERR_UNSUPPORTED;
        }

        TspdfObj *params = decode_params_at(stream_dict, i);
        size_t decoded_len = 0;
        TspdfError err = TSPDF_OK;
        uint8_t *decoded = tspdf_filter_decode((const char *)filter_name->string.data,
                                               current, current_len, params,
                                               &decoded_len, &err);
        free(current);
        if (err != TSPDF_OK) {
            return err;
        }
        current = decoded;
        current_len = decoded_len;
    }

    *out_data = current;
    *out_len = current_len;
    return TSPDF_OK;
}
